# Generated by Django 3.1 on 2020-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                (
                    'num_vote_down',
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
    ]
