# Generated by Django 3.1 on 2020-09-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='post.post',
            ),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_post_user_id_57d352_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['post'], name='post_image_post_id_4c6280_idx'),
        ),
    ]
