# Generated by Django 3.1 on 2020-09-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0002_bookmark_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bookmarks',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(
                fields=['post', 'user'], name='bookmark_bo_post_id_85bc5a_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark', unique_together={('post', 'user')},
        ),
    ]
