# Generated by Django 3.1 on 2020-09-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='requester',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='to_follow',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='followrequest',
            index=models.Index(
                fields=['to_follow'], name='feed_follow_to_foll_719619_idx'
            ),
        ),
    ]
